[03/08/2018 19:28] ERROR red load_cogs 573: module 'discord' has no attribute 'Channel'
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\Jack Crispy\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Jack Crispy\Desktop\Red-DiscordBot-develop\cogs\audio.py", line 310, in <module>
    class Audio:
  File "C:\Users\Jack Crispy\Desktop\Red-DiscordBot-develop\cogs\audio.py", line 1190, in Audio
    async def audioset_notifychannel(self, ctx, channel: discord.Channel):
AttributeError: module 'discord' has no attribute 'Channel'
[03/08/2018 19:28] ERROR red load_cogs 573: You need the imgurpython module to use this.
pip3 install imgurpython
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\Jack Crispy\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "C:\Users\Jack Crispy\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 699, in load_extension
    lib.setup(self)
  File "C:\Users\Jack Crispy\Desktop\Red-DiscordBot-develop\cogs\image.py", line 165, in setup
    raise RuntimeError("You need the imgurpython module to use this.\n"
RuntimeError: You need the imgurpython module to use this.
pip3 install imgurpython
[03/08/2018 19:28] ERROR red load_cogs 573: module 'discord' has no attribute 'Channel'
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\Jack Crispy\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Jack Crispy\Desktop\Red-DiscordBot-develop\cogs\mod.py", line 92, in <module>
    class Mod:
  File "C:\Users\Jack Crispy\Desktop\Red-DiscordBot-develop\cogs\mod.py", line 147, in Mod
    async def modlog(self, ctx, channel : discord.Channel=None):
AttributeError: module 'discord' has no attribute 'Channel'
[03/08/2018 19:28] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:28] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:29] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:30] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:31] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:31] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:31] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:31] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:31] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:31] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:31] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:31] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:31] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:31] ERROR red load_cogs 573: cogs.streams
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\Jack Crispy\Desktop\Red-DiscordBot-develop\cogs\owner.py", line 944, in _load_cog
    raise CogNotFoundError(cogname)
cogs.owner.CogNotFoundError: cogs.streams
[03/08/2018 19:31] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:32] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:32] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:32] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:32] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:32] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:32] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:32] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[03/08/2018 19:32] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Jack Crispy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
